version: 2
updates:
  - package-ecosystem: npm
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: America/Cancun
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
    groups:
      development-dependencies:
        dependency-type: development
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - version-update:semver-major
      - dependency-name: "@lingui/babel-plugin-lingui-macro"
        update-types:
          - version-update:semver-major

  - package-ecosystem: github-actions
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
      day: monday
      time: "08:30"
      timezone: America/Cancun
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci(deps)"
